### ISSUE TITLE
Plugin can be enabled in the Site context, but will not work correctly.

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/pkp-formHoneypot#4]
Navigating to Administration -> Site Settings -> Plugins will allow the plugin to be enabled within the Site context.  The code for configuring the settings and for displaying the honeypot is all journal specific, though.

**Comment by alex-wreschnig** [comment]
As part of making this plugin work for the site-context registration page, we needed to convert this plugin to be a site-wide plugin. The site was developed as a journal-context plugin for the 2.x branch initially, which gave journal editors configuration control of the plugin for each individual journal. This was important because the most common implementation reused an existing field. Unlike in 2.x, the 3.x version of the plugin can't appropriate existing fields; the only remaining configuration is setting the timeout window. (The registration form is, to its credit, much shorter; there isn't a good selection of existing fields for the plugin to make use of.)

Because the plugin can't be both site-context and journal-context at the same time, this change is going to result in a slight loss of control for journal editors. We hope that complete coverage of all registration forms will make up for it.

**Comment by alex-wreschnig** [comment]
The closing commit was merged and squashed.
